name: Test PowerShell on Ubuntu
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Import BasicMathFunctions Module
        shell: pwsh
        run: |
          Import-Module BasicMathFunctions.psm1 
      - name: Perform a Pester test from the BasicMathFunctions.Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester BasicMathFunctions.Tests.ps1 -Passthru